osx_image: xcode7.2
language: objective-c
xcode_project: Spectacle.xcodeproj
xcode_scheme: Spectacle

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap

script:
  - xctool -project Spectacle.xcodeproj -scheme Spectacle test
